Feat/#5 course
sparta-team5/BackOffice pull request #7
Opened 2024-06-12 11:50 UTC by Poucqc

Implement Course API

2024-06-12 12:19 UTC, AWKRID requested changes
전체적으로 toResponse형태의 함수를 service에서 많이 활용하고 계신데, dto의 from 함수를 이용하는 것으로 수정 부탁드립니다.

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/dto/CourseListResponse.kt
> +    val rate: Int?
아마도 여기 들어가는 rate의 경우 추후에 고려하겠지만 소수점 형태로 반영될 것 같아서 Double이 괜찮을 것 같네요! nullable은 하지 않도록 진행하면 좋을 것 같습니다.

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/dto/CourseListResponse.kt
> +data class CourseListResponse(
Id를 반드시 포함시켜야 할 것 같습니다

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/dto/CourseResponse.kt
> +data class CourseResponse(
여기도 마찬가지로 Id가 필요합니다.

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/dto/CourseSimpleResponse.kt
> +data class CourseSimpleResponse(
동일하게 Id 포함해주세요

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/dto/FilteringDto.kt
> +    val category: Category,
Category는 String으로 가져올 것 같습니다.

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/model/Category.kt
> +enum class Category {
이걸 코드 단에서 작성하는 것이 아닌 DB에 작성해서 가져오도록 ERD에 포함시켰습니다. Enum으로 따로 관리하지 않으셔도 될 것 같습니다.

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/model/Course.kt
> +fun Course.toResponse(isBookMarked: Boolean, isSubscribed: Boolean): CourseResponse {
Response쪽에 from함수가 있기 때문에 toResponse 형태의 함수는 제거해주시면 될 것 같습니다.

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/service/CourseService.kt
> +                it.toListResponse(
dto의 from 함수를 활용해서 수정해주세요

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/service/CourseService.kt
> +            course.toResponse(existBookmark(studentId, courseId), existSubscribe(studentId, courseId))
여기도 from 함수 활용 부탁드립니다

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/service/CourseService.kt
> +                it.toListResponse(
여기도 from 함수 활용 부탁드립니다

2024-06-12 12:19 UTC, AWKRID commented on src/main/kotlin/domain/course/service/CourseService.kt
> +        ).toSimpleResponse()
여기도 from 함수 활용 부탁드립니다

2024-06-12 12:49 UTC, Poucqc commented on src/main/kotlin/domain/course/dto/CourseListResponse.kt
> +    val rate: Int?
반영했습니다

2024-06-12 12:49 UTC, Poucqc commented on src/main/kotlin/domain/course/dto/CourseListResponse.kt
> +data class CourseListResponse(
반영했습니다

2024-06-12 12:50 UTC, Poucqc commented on src/main/kotlin/domain/course/dto/CourseResponse.kt
> +data class CourseResponse(
:wrench:

2024-06-12 12:50 UTC, Poucqc commented on src/main/kotlin/domain/course/dto/CourseSimpleResponse.kt
> +data class CourseSimpleResponse(
:wrench:

2024-06-12 12:51 UTC, Poucqc commented on src/main/kotlin/domain/course/dto/FilteringDto.kt
> +    val category: Category,
:wrench:

2024-06-12 12:51 UTC, Poucqc commented on src/main/kotlin/domain/course/model/Category.kt
> +enum class Category {
:wrench:

2024-06-12 12:51 UTC, Poucqc commented on src/main/kotlin/domain/course/model/Course.kt
> +fun Course.toResponse(isBookMarked: Boolean, isSubscribed: Boolean): CourseResponse {
:wrench:

2024-06-12 12:51 UTC, Poucqc commented on src/main/kotlin/domain/course/service/CourseService.kt
> +                it.toListResponse(
:wrench:

2024-06-12 12:51 UTC, Poucqc commented on src/main/kotlin/domain/course/service/CourseService.kt
> +            course.toResponse(existBookmark(studentId, courseId), existSubscribe(studentId, courseId))
:wrench:

2024-06-12 12:51 UTC, Poucqc commented on src/main/kotlin/domain/course/service/CourseService.kt
> +                it.toListResponse(
:wrench:

2024-06-12 12:51 UTC, Poucqc commented on src/main/kotlin/domain/course/service/CourseService.kt
> +        ).toSimpleResponse()
:wrench:

2024-06-12 13:11 UTC, taehuiii approved these changes
고생하셨습니다! 개인적으로 궁금한 부분 몇가지 코멘트 남겨두었습니다 ☺️

2024-06-12 13:11 UTC, taehuiii commented on src/main/kotlin/domain/course/model/Course.kt
> +    @OneToMany(mappedBy = "course", orphanRemoval = true)
review, lecture와 양방향 연결을 위해  @OneToMany를 사용하신건가요?! 양방향연관관계가 필요하다고 생각하신 이유가 궁금합니다..!!

2024-06-12 13:11 UTC, taehuiii commented on src/main/kotlin/domain/course/model/Course.kt
> +fun Course.toResponse(isBookMarked: Boolean, isSubscribed: Boolean): CourseResponse {
toResponse 함수는 dto부분에 companion object내에 구현되어있는데 entity에도 남겨두신 이유가 이유가 있을까요 ?

2024-06-12 13:11 UTC, taehuiii commented on src/main/kotlin/domain/course/service/CourseService.kt
> +                    existBookmark(studentId, it.id!!),
전체 course조회에서 bookmark와 subscription을 확인하는 이유는 사용자가 해당 코스를 이미 북마크/결제를 했는지 유무를 표시해주기 위함인가요 ?!

2024-06-12 13:11 UTC, taehuiii commented on src/main/kotlin/domain/course/service/CourseService.kt
> +    fun updateCourseById(courseId: Long, request: CourseRequest, tutorId: Long): CourseSimpleResponse {
course 수정, 삭제에 대한 권한이 있는지 ( 작성자인지) 확인하는 로직이 필요할 것 같습니다! todo로라도 간단하게 작성해두면 좋을 것 같아요

2024-06-12 13:11 UTC, taehuiii commented on src/main/kotlin/domain/course/service/CourseService.kt
> +            student.bookmark.add(course)
student에 bookmark 필드가 존재하지 않는데,  bookmark entity에서 id를 추가하여 관리하는 방법보다 student에 bookmark를 추가하는것이 더 좋다고 생각하신 이유가 있으신지 궁금합니다!!

2024-06-12 14:23 UTC, DEVxMOON approved these changes
전체적으로 잘 봤습니다. 다만, 제가 흐름을 우선시해서 보는 편이라 완전 상세한 포멧팅 관련 피드백은 부족할 것 같아요. (작성해주신 코드가 동작하는 방식은 알아보기 좋았습니다👍)
id 관련은 다른분들이 피드백 해주신거 확인해서 별도로 첨언하진 않겠습니다.

2024-06-12 14:23 UTC, DEVxMOON commented on src/main/kotlin/domain/course/dto/CursorRequest.kt
> +data class CursorRequest(
전체 정렬 방식 자체는 나중에 Lecture에서 구현한 방식을 일치시키긴 해야겠네요 ( 나중에 )

2024-06-13 00:06 UTC, Poucqc commented on src/main/kotlin/domain/course/model/Course.kt
> +    @OneToMany(mappedBy = "course", orphanRemoval = true)
orpahnRemoval 을 어떻게 할지 결정이 안되있기 때문에 표시를 위해 일단 관계를 맺어두었습니다.
만약 로직에서 직접 처리할 경우 이부분을 지우고 서비스 단계에서 처리할 예정입니다

2024-06-13 00:07 UTC, Poucqc commented on src/main/kotlin/domain/course/model/Course.kt
> +fun Course.toResponse(isBookMarked: Boolean, isSubscribed: Boolean): CourseResponse {
dto쪽에서 from 을 쓴다고 하기 전에 미리 작성해둔 부분이라 삭제가 늦었습니다

2024-06-13 00:07 UTC, Poucqc commented on src/main/kotlin/domain/course/service/CourseService.kt
> +                    existBookmark(studentId, it.id!!),
네 만약 로그인한 사용자가 목록조회를 했을경우 북마크/구독 유무를 표시해 줘야 한다고 생각했습니다

2024-06-13 00:09 UTC, Poucqc commented on src/main/kotlin/domain/course/service/CourseService.kt
> +    fun updateCourseById(courseId: Long, request: CourseRequest, tutorId: Long): CourseSimpleResponse {
if (tutorId != course.tutor.id) 로 표현해 두었습니다

2024-06-13 00:09 UTC, Poucqc commented on src/main/kotlin/domain/course/service/CourseService.kt
> +            student.bookmark.add(course)
studuent쪽 필드를 보지 않은 상태에서 작성한 부분이라 제가 임시로 적어두었습니다.
bookmark 필드가 생긴다면 바로 수정하겠습니다

2024-06-13 00:10 UTC, Poucqc commented on src/main/kotlin/domain/course/dto/CursorRequest.kt
> +data class CursorRequest(
:white_check_mark:

2024-06-13 00:11 UTC, AWKRID requested changes
response 관련 dto에 들어가는 id가 전반적으로 자신의 domain name이 붙어있습니다.
id로 통일해주시면 감사하겠습니다.

2024-06-13 00:11 UTC, AWKRID commented on src/main/kotlin/domain/course/dto/CourseListResponse.kt
> +data class CourseListResponse(
변수 명을 courseId가 아닌 id로 해주세요. 또한, dto에서는 Id가 nullable하지 않아야 할 것 같습니다.

2024-06-13 00:17 UTC, Poucqc commented on src/main/kotlin/domain/course/dto/CourseListResponse.kt
> +data class CourseListResponse(
✅

2024-06-13 00:19 UTC, AWKRID approved these changes

2024-06-13 00:20 UTC, merged